# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhilsNotesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='builder',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobnote',
            name='note_date',
            field=models.DateField(db_index=True),
        ),
    ]
