# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhilsNotesApp', '0002_auto_20180810_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='builder',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='cell_phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='email_1',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='job',
            name='email_2',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='job',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
