# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhilsNotesApp', '0003_auto_20180810_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='builder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PhilsNotesApp.Builder'),
        ),
    ]
