# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhilsNotesApp', '0004_auto_20180810_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PhilsNotesApp.Builder'),
        ),
    ]
