# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-13 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhilsNotesApp', '0005_auto_20180810_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builder',
            options={'verbose_name': 'Builder', 'verbose_name_plural': 'Builders'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobnote',
            options={'verbose_name': 'Job Note', 'verbose_name_plural': 'Job Notes'},
        ),
        migrations.AlterField(
            model_name='jobnote',
            name='note_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
